# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_vkpost_new_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkpost',
            name='date',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
