# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0016_auto_20180329_1417'),
        ('news', '0004_vkpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkpost',
            name='article',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='aldryn_newsblog.Article'),
            preserve_default=False,
        ),
    ]
