# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180829_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='vk',
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='accounts.Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='scholarship',
            field=models.FloatField(default=0),
        ),
    ]
