# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_start', models.DateField()),
                ('application_end', models.DateField()),
                ('period_start', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='claim',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_service.Period'),
        ),
    ]
