# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_service', '0002_auto_20180829_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='period_end',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
