# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_service', '0004_period_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='application_type',
            field=models.CharField(choices=[('A', 'Бесплатное питание'), ('B', 'Профилакторий'), ('C', 'Ежемесячный АПОС'), ('D', 'Единоразовый АПОС')], default=None, max_length=1),
            preserve_default=False,
        ),
    ]
