# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_service', '0005_period_application_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='application_type',
            field=models.CharField(choices=[('Бесплатное питание', 'Бесплатное питание'), ('Профилакторий', 'Профилакторий'), ('Ежемесячный АПОС', 'Ежемесячный АПОС'), ('Единоразовый АПОС', 'Единоразовый АПОС')], max_length=30),
        ),
    ]
