# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_service', '0006_auto_20180829_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='affected_by_chernobyl',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='is_orphan',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='lives_in_dormitory',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='sms_notification',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
