# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_service', '0008_auto_20180919_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='from_incomlete_family',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='from_poor_family',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='has_chronic_illness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='has_no_scholarship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='is_in_severe_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='is_one_of_many_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='is_participant_of_hostilities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='parents_are_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='period',
            name='application_type',
            field=models.CharField(choices=[('apos_single', 'Единоразовый АПОС'), ('profilaktory', 'Профилакторий'), ('apos_regular', 'Ежемесячный АПОС'), ('meals', 'Бесплатное питание')], max_length=30),
        ),
    ]
