# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0010_auto_20180414_2058'),
        ('social_service', '0009_auto_20180919_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='documents',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_documents', to='filer.File'),
        ),
        migrations.AlterField(
            model_name='period',
            name='application_type',
            field=models.CharField(choices=[('profilaktory', 'Профилакторий'), ('apos_regular', 'Ежемесячный АПОС'), ('meals', 'Бесплатное питание'), ('apos_single', 'Единоразовый АПОС')], max_length=30),
        ),
    ]
