# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_service', '0012_auto_20180920_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='application_type',
            field=models.CharField(choices=[('apos_regular', 'Ежемесячный АПОС'), ('meals', 'Бесплатное питание'), ('profilaktory', 'Профилакторий'), ('apos_single', 'Единоразовый АПОС')], max_length=30),
        ),
    ]
