# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_service', '0013_auto_20180920_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'На рассмотрении')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='claim',
            name='status_assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='status_reason',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='period',
            name='application_type',
            field=models.CharField(choices=[('profilaktory', 'Профилакторий'), ('apos_regular', 'Ежемесячный АПОС'), ('apos_single', 'Единоразовый АПОС'), ('meals', 'Бесплатное питание')], max_length=30),
        ),
    ]
