# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_service', '0014_auto_20180921_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='additional_information',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='claim',
            name='canteen_preference',
            field=models.CharField(choices=[('3rd', 'Столовая 3-ки'), ('kpm', 'Столовая КПМ'), ('equal', 'Без разницы')], default='equal', max_length=8),
        ),
        migrations.AlterField(
            model_name='claim',
            name='affected_by_chernobyl',
            field=models.BooleanField(default=False, verbose_name='Чернобылец'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='from_incomlete_family',
            field=models.BooleanField(default=False, verbose_name='Из неполной семьи'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='from_poor_family',
            field=models.BooleanField(default=False, verbose_name='Из неблагополучной семьи'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='has_children',
            field=models.BooleanField(default=False, verbose_name='Есть дети'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='has_chronic_illness',
            field=models.BooleanField(default=False, verbose_name='Нахожусь на диспансерном учете с хроническим заболеванием'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='has_no_scholarship',
            field=models.BooleanField(default=False, verbose_name='Нет стипендии'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Инвалид'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='is_in_severe_conditions',
            field=models.BooleanField(default=False, verbose_name='Тяжелое материальное положение'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='is_one_of_many_children',
            field=models.BooleanField(default=False, verbose_name='Из многодетной семьи'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='is_orphan',
            field=models.BooleanField(default=False, verbose_name='Сирота'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='is_participant_of_hostilities',
            field=models.BooleanField(default=False, verbose_name='Участник боевых действий'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='lives_in_dormitory',
            field=models.BooleanField(default=False, verbose_name='Проживаю в общежитии'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='parents_are_disabled',
            field=models.BooleanField(default=False, verbose_name='Родители-инвалиды (или пенсионеры)'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='sms_notification',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'На рассмотрении')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='period',
            name='application_type',
            field=models.CharField(choices=[('apos_single', 'Единоразовый АПОС'), ('profilaktory', 'Профилакторий'), ('apos_regular', 'Ежемесячный АПОС'), ('meals', 'Бесплатное питание')], max_length=30),
        ),
    ]
