# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_service', '0015_auto_20180926_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='application_type',
            field=models.CharField(choices=[('apos_single', 'Единоразовый АПОС'), ('apos_regular', 'Ежемесячный АПОС'), ('profilaktory', 'Профилакторий'), ('meals', 'Бесплатное питание')], max_length=30),
        ),
    ]
