# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_service', '0016_auto_20181013_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='application_type',
            field=models.CharField(choices=[('apos_regular', 'Ежемесячный АПОС'), ('apos_single', 'Единоразовый АПОС'), ('meals', 'Бесплатное питание'), ('profilaktory', 'Профилакторий')], max_length=30),
        ),
    ]
