# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_service', '0017_auto_20181013_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='application_type',
            field=models.CharField(choices=[('meals', 'Бесплатное питание'), ('apos_single', 'Единоразовый АПОС'), ('profilaktory', 'Профилакторий'), ('apos_regular', 'Ежемесячный АПОС')], max_length=30),
        ),
    ]
